apiVersion: apps/v1
kind: Deployment
metadata:
  name: endoflife-datastore
  labels:
    app: endoflife-datastore
spec:
  replicas: {{ .Values.datastore.replicas }}
  selector:
    matchLabels:
      app: endoflife-datastore
  template:
    metadata:
      labels:
        app: endoflife-datastore
    spec:
      serviceAccountName: {{ .Values.rbac.serviceAccount.name }}
      containers:
        - name: datastore
          image: "{{ .Values.datastore.image.repository }}:{{ .Values.datastore.image.tag }}"
          imagePullPolicy: {{ .Values.datastore.image.pullPolicy }}
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: datastore-config
                  key: mongodbUri
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: datastore-config
                  key: logLevel
            - name: WATCH_NAMESPACE
              value: default
            - name: MONGODB_DATABASE
              value: {{ .Values.datastore.config.mongodbDatabase }}
            - name: MONGODB_COLLECTION
              value: {{ .Values.datastore.config.mongodbCollection }}
